FROM apache/airflow:2.8.1
USER root

RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

USER airflow
RUN pip install --no-cache-dir 'dbt-core>=1.8,<1.9' 'dbt-trino>=1.8,<1.9'
