"""Constants for MIC-34 bounded-run generator."""

SCENARIO_NORMAL_BASELINE = "normal_baseline"
SCENARIO_VIRAL_HIGH_QUALITY = "viral_high_quality"
SCENARIO_VIRAL_LOW_QUALITY = "viral_low_quality"
SCENARIO_COLD_START_UNDER_EXPOSED = "cold_start_under_exposed"
SCENARIO_INVALID_PAYLOAD_BURST = "invalid_payload_burst"

SCENARIO_KEYS = (
    SCENARIO_NORMAL_BASELINE,
    SCENARIO_VIRAL_HIGH_QUALITY,
    SCENARIO_VIRAL_LOW_QUALITY,
    SCENARIO_COLD_START_UNDER_EXPOSED,
    SCENARIO_INVALID_PAYLOAD_BURST,
)

ACTION_NO_ACTION = "NO_ACTION"
ACTION_BOOST = "BOOST"
ACTION_REVIEW = "REVIEW"
ACTION_RESCUE = "RESCUE"
ACTION_INVALID_SINK = "INVALID_SINK"

SCENARIO_TO_ACTION = {
    SCENARIO_NORMAL_BASELINE: ACTION_NO_ACTION,
    SCENARIO_VIRAL_HIGH_QUALITY: ACTION_BOOST,
    SCENARIO_VIRAL_LOW_QUALITY: ACTION_REVIEW,
    SCENARIO_COLD_START_UNDER_EXPOSED: ACTION_RESCUE,
    SCENARIO_INVALID_PAYLOAD_BURST: ACTION_INVALID_SINK,
}

ACTION_REASON_CODES = {
    ACTION_NO_ACTION: [],
    ACTION_BOOST: ["HIGH_VELOCITY_P90", "GATE_PASS"],
    ACTION_REVIEW: ["HIGH_VELOCITY_P90", "LOW_COMPLETION", "HIGH_SKIP"],
    ACTION_RESCUE: ["NEW_UPLOAD_LT_60M", "UNDER_EXPOSED_P40", "GATE_PASS"],
    ACTION_INVALID_SINK: ["MALFORMED_PAYLOAD"],
}

ALLOWED_EVENT_TYPES = (
    "impression",
    "play_start",
    "play_finish",
    "like",
    "share",
    "skip",
)

DEFAULT_SCHEMA_VERSION = "m1_v1"
DEFAULT_CDC_GATE_SECONDS = 300

TOPIC_CONTENT_EVENTS = "content_events"
TOPIC_CDC_VIDEOS = "cdc.content.videos"
